 # 11. 异常

## **Throwable类 -- 错误和异常的父类**
## **Error类 -- 系统错误类，程序终结如：**
1. 虚拟机错误
2. 内存溢出
3. 线程死锁
## **Exception -- 异常类，编码、环境、用户操作输入出现问题**

**RuntimeException -- 运行时异常,非检查异常，由java虚拟机自动抛出并自动捕获**

  异常是指不期而至的各种状况，如：文件找不到，网络连接失败，非法参数等。 异常是一个事件，他发生在程序运行期间，干扰了正常的指令流程。
  类型转换异常
  Throwable  异常的根类
  ArithmeticException 算术异常
  ArrayIndexOutOfBoundsException 数组角标越界
  NullPointerException 空指针异常
  NumberFoNumberFormatException 数字格式错误

**异常分类**

  编译时异常：编译代码时通不过的
  运行时异常：编译时正常，运行时异常
## 捕获异常处理
- try…catch 语句，try…catch…finally 语句，try…finally语句
- 调用有抛出异常的方法必须使用try捕获
  - try 块：用于捕获异常。其后可以接零个或多个catch块，如果没有catch块，则必须跟一个finally。
  - catch 块：用于处理try捕获到的异常。
  - finally块；无论是否捕获或处理，finally块里的语句都会被执行。

异常的三种格式

    try{//捕获异常
        //写可能出现异常的代码，可以有很多句代码
    }catch(异常类型 变量名){
    //处理异常,并不是把上面的代码改正确，常见的一些方式：
      1. 打印异常的消息到控制
    }catch(){  
    }catch(){
    }finally{//无论try执行还是catch执行都会执行finally，可以做一些收尾或清理工作 
    }


    try{    
    }catch(){
    }


    try{    
    }finally{
    }
- 如果try中的语句发送了异常，那么try中的代码块会停止执行
- 然后执行catch中的代码块
- 执行完成后会执行try catch后面的代码块

**多个catch块处理异常**

- 如果try中语句可能有多种异常产生，那么我们就要用多个catch块来处理不同的异常
    private static void method2() {
        try {
            Scanner scanner = new Scanner(System.in);
            System.out.println("请输入被除数：");
            int firstNum = scanner.nextInt();
            System.out.println("请输入被除数：");
            int secondNum = scanner.nextInt();
            int quotient = firstNum / secondNum;
            System.out.println(firstNum + "/" + secondNum + "=" + quotient);
        } catch (InputMismatchException e) {
            e.printStackTrace();
        } catch (ArithmeticException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
- 使用多个catch块的注意事项一定要注意顺序：从上到下，一定是从小到大的异常类，也就是子类到父类
![](http://owq30xt9s.bkt.clouddn.com/%E5%BC%82%E5%B8%B8%E7%BB%93%E6%9E%84%E5%9B%BE.png)


**使用try catch finally 处理异常**


-  有些操作是不管我们出不出异常都需要执行的，那么这些操作就应该放在finally中
        private static void method3() {
                try {
                        
                } catch (Exception e) {
                        // TODO: handle exception
                } finally {
                        
                }
        }
    




## **抛出异常**
- 我们可以不及时处理而是将异常抛出，然后让该方法的调用者来处理异常或再次抛出

**throws关键字**

- 用在方法上，表明该方法有可能抛出一种或多种异常
- 方法上默认抛出 `RuntimeException` 异常

**throw关键字**

- 用在方法里，将产生的异常抛出

**抛出异常处理**

- 声明方法时使用throws抛出
- 语法：
     methodname() throws Exception1, Expception2….,ExceptionN{
     …
     }

在调用使用了`throws`抛出异常的方法时，要么try处理，要么继续抛出

## **自定义异常**
- 自定义一个异常类，让他继承自Java中原来有的意思相近的异常，也可以直接继承自Exception类
    package com.fs.test;
    
    public class NoNetException extends Exception{
            public NoNetException() {
                    // TODO Auto-generated constructor stub
            }
            
            public NoNetException (String message) {
                    super(message);
            }
    }

常见异常


  

